add g8scontrolplane validation
giantswarm/aws-admission-controller pull request #75
Opened 2020-09-30 11:56 UTC by anvddriesch

2020-09-30 12:48 UTC, njuettner approved these changes
Cool 🚀, when you have time adding a test would be awesome. But I know it's in progress 🙂

2020-10-02 14:07 UTC, njuettner requested changes
You need to add webhook config for g8scontrolplane, see https://github.com/giantswarm/aws-admission-controller/blob/master/helm/aws-admission-controller/templates/webhook.yaml#L94

2020-10-02 14:07 UTC, njuettner commented on pkg/unittest/default_admission_request.go
> +			Kind:    "AWSControlPlane",
```suggestion
			Kind:    "G8sControlPlane",
```

2020-10-02 14:07 UTC, njuettner commented on pkg/unittest/default_admission_request.go
> +			Resource: "awscontrolplanes",
```suggestion
			Resource: "g8scontrolplanes",
```

2020-10-02 14:12 UTC, njuettner commented on pkg/aws/g8scontrolplane/validate_g8scontrolplane.go
> +			v.Log("level", "debug", "message", fmt.Sprintf("No AWSControlPlane %s could be found: %v", g8sControlPlane.GetName(), err))
Maybe also add the cluster id, wdyt?

2020-10-05 13:43 UTC, anvddriesch commented
I added the webhook config and tested this on `giraffe`. It's working.
```
Error from server: error when creating "testg8scp.yaml": admission webhook "g8scontrolplanes.aws-admission-controller-unique.giantswarm.io" denied the request: not allowed error: G8sControlPlane gcat9 with 1 replicas does not match AWSControlPlane gcat9 with 3 availability zones [cn-north-1a cn-north-1a cn-north-1b]
```

2020-10-05 15:40 UTC, njuettner approved these changes
cool 👍

2020-10-06 11:20 UTC, merged